table Dim_Vendedor
	lineageTag: af75a9ba-2584-4277-b5ed-b20c5aaa7b29

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: fd965d0a-a8bb-4aa2-800e-71c61f8593f0
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 236f58de-b772-4e0e-956b-53eb4d7cbde1
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 67575dab-88e9-499f-a333-29a1135b2df4
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variation
			isDefault
			relationship: b3b60ee3-fee2-41ea-8c72-79280700f1f8
			defaultHierarchy: LocalDateTable_3013e7fe-18f8-428c-933b-aa98a5043209.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: 116c66a3-ef91-4864-beb1-bdaedf12c0e8
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Dim_Vendedor = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\elise\Desktop\VentasVehiculos.xlsx"), null, true),
				    Dim_Vendedor_Table = Source{[Item="Dim_Vendedor",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Vendedor_Table,{{"ID_Vendedor", Int64.Type}, {"Vendedor", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

